version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: gostack_desafio06
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432

  db_test:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: gostack_desafio06_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    ports:
      - 5433:5432
